### ISSUE TITLE
Origami deps are getting out of date

### ISSUE THREAD

**Issue by aendrew** [Financial-Times/g-components#92]
I tried to install o-loading latest and got deeply stuck in Bower Dependency Hell. I take this to mean we need to update a lot of stuff from Origami. Given we're also in the midsts of General Election Hell:

![ain't nobody got time for that](https://media.giphy.com/media/10PcMWwtZSYk2k/giphy.gif)

Somebody please fix this when we have time and better headspace.

**Comment by notlee** [comment]
Haha, yeah, this is because we released new major versions of low level components (and all the components that depended on them). 

Customer Products have mostly done upgrading now so the new versions have been tried and tested. When you're ready to upgrade all the things too there's the usual migration guides for each component in the README. And there's also more context in this [blog post](https://origami.ft.com/blog/2019/10/31/major-cascade/) and these [slides](https://docs.google.com/presentation/d/1_SRer70OQkwFe5I8eB513fOqjLYeMno0mxoRVVBbFpE/edit#slide=id.g6b941a3907_2_8) I put together for Customer Products.  Let me know if I can help in any.

P.s... no more CommonJS in Origami components! 😄🎉

**Comment by aendrew** [comment]
Cheers, thanks @notlee — I'm on an embed with the Tech Desk for the next two weeks but will track you down once I'm back to BAU. :+1: 

Unless anyone else wants to do this in the meantime...? 🤷🏼‍♀️
